---
title: "WORK-HOMEWORK"
author: "JEFFREY BLAY"
date: "2023-05-09"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LOADING LIBRARIES
```{r}
library(dplyr)
library(ggplot2)
library(reshape2)
```


# GHG INVENTORY DATASETS

#SECTION 1

```{r}
#Loadind data
# Petroleum systems
ps <- read.csv("C:/Users/jeffr/Dropbox (YSE)/Personal/CV's/EDF/Datasets/Working data/Table 3-45.csv")

#CLeaning column names
colnames(ps) <- gsub("X","",colnames(ps))


#Removing commas
r_c <- function(x){
  gsub(",","",x)
}
ps[] <- lapply(ps,r_c)

head(ps)

#subsetting production segment

prd <- ps[c(3,5,6,7,8,9),]
head(prd,8)

prd <- prd %>% mutate_at(vars(2:33),as.integer) #Converting variables to integers
head(prd)


# Natural Gas
ns <- read.csv("C:/Users/jeffr/Dropbox (YSE)/Personal/CV's/EDF/Datasets/Working data/Table 3-67.csv")

#Changing column names
colnames(ns) <- gsub("X","",colnames(ns))
head(ns,12)

#Subsetting onshore production
npd <- ns[3,]
head(npd)

#Combining Petroleum and Natural Gas Production
all <- rbind(prd, npd) #combining data
all

#Calculating the total production emissions for each year
sum <- apply(all[, 2:33 ], 2, sum) #summing variables

new_row <- data.frame(Segment="Total", t(sum)) # Creating a dataframe for total calculation
colnames(new_row) <- gsub("X","",colnames(new_row)) # cleaning column of new dataframe
allT <- rbind(all, new_row)#combining data
head(allT,9)

#Getting the total methane emissions from Onshore production(Natural gas and Petroleum)
print(paste("Total methane emissions from onshore Natural Gas and Petroleum systems production is",  allT[8 ,'2021'], "kt CH4"))

#write.csv(allT,"C:/Users/jeffr/Dropbox (YSE)/Personal/CV's/EDF/Datasets/Working data/total.csv")
```

#Plotting Time trend

```{r}
trend <- allT[8, ]#filtering total
head(trend)

melt <- melt(trend)#converting data from wide to long
head(melt)

xcoord <- melt$variable[which.max(melt$value)]#maximum value
ggplot(melt, aes(x=variable, y= value,group = 1)) + 
  geom_line(color="orange",size=1.5) +
  geom_vline(xintercept = xcoord, color = "blue", linetype = "dashed",size = 1) +
  annotate("text", x = xcoord, y = max(melt$value), label = max(melt$value), color='black',size = 5,fontface = "bold") +
  xlab("Year") + 
  ylab("Methane Emission (kt CH4)") +
  labs(title = "Methane Emissions from onshore Natural Gas and Petroleum systems Production (1990-2021)") +
  theme_classic() + 
  theme(axis.text = element_text(face = "bold"),
        plot.caption = element_text(face = "bold"),
        axis.text.x = element_text(angle = 90,vjust = 0.5, hjust=1)) 


```
#Section 2- policy 1 - 60 percent reduction in metric tonnes

```{r}
#Loadind data
# Petroleum systems
ps_mt <- read.csv("C:/Users/jeffr/Dropbox (YSE)/Personal/CV's/EDF/Datasets/Working data/Table 3-44.csv")

#Changing column names
colnames(ps_mt) <- gsub("X","",colnames(ps_mt))
head(ps_mt)

#subsetting production segment

prd_mt <- ps_mt[c(3,5,6,7,8,9),]
head(prd_mt,8)

prd_mt <- prd_mt %>% mutate_at(vars(2:33),as.integer) #Converting variables to integers
head(prd_mt)


# Natural Gas
ns_mt <- read.csv("C:/Users/jeffr/Dropbox (YSE)/Personal/CV's/EDF/Datasets/Working data/Table 3-66.csv")

#Changing column names
colnames(ns_mt) <- gsub("X","",colnames(ns_mt))
head(ns_mt,12)

#Subsetting onshore production
npd_mt <- ns_mt[3,]
head(npd_mt)

#Combining Petroleum and Natural Gas Production
all_mt <- rbind(prd_mt, npd_mt)#combining data
all_mt

#Calculating the total production emissions for each year
sum <- apply(all_mt[, 2:33 ], 2, sum)#summing variables

new_row_mt <- data.frame(Segment="Total", t(sum)) # Creating a dataframe for total calculation
colnames(new_row_mt) <- gsub("X","",colnames(new_row_mt)) # cleaning column of new dataframe
allT_mt <- rbind(all_mt, new_row_mt)#combining data
head(allT_mt,9)

#write.csv(allT_mt,"C:/Users/jeffr/Dropbox (YSE)/Personal/CV's/EDF/Datasets/Working data/2015_21_mt.csv")

#Melting
trend <- allT_mt[8, ]#filtering total
head(trend)

melt_mt <- melt(trend,id= 'Segment')
head(melt_mt)

#Subsetting 2015-2021 datasets

melt_mt$variable <- as.character(melt_mt$variable)
melt_mt$variable<- as.numeric(melt_mt$variable)

rd_mt <- melt_mt[melt_mt$variable >= 2015, ]
head(rd_mt)

#Estimating 60 percent emissions
rd_mt$reduction <- rd_mt$value - (60/100*rd_mt$value)
rd_mt$diff_60 <- 60/100*rd_mt$value
head(rd_mt)

#Filtering
rd_mt <- rd_mt[, 2:5]
colnames(rd_mt) <- c("Year","Total_Emission","Emission_after_Reduction","Emission_Reduction_Value(60%)") #Changing column names
head(rd_mt)

#Melting data
m_mt <- melt(rd_mt,id = "Year")
head(m_mt)

#Plotting.

ggplot(data=m_mt, aes(x=Year, y=value, group=variable)) +
  geom_line(aes(color=variable))+
  scale_x_continuous(n.breaks = 6)+
  geom_point(aes(color=variable)) +
  labs(title = "Associated Emission Reduction (2015-2021)") +
  ylab("Methane Emission (metric tons CH4)") +
  geom_label(aes(label = paste(value)), 
            position = position_dodge(width = 0.3), vjust = -0.25) +
  theme_classic()

```
#SECTION 3

```{r}
#Loading data
all_3 <- read.csv("C:/Users/jeffr/Dropbox (YSE)/Personal/CV's/EDF/Datasets/Working data/all_3.csv")
head(all_3)

#Changing column names
colnames(all_3) <- gsub("X","",colnames(all_3))
head(all_3,12)

```


```{r}
#POLICY 1
# 95 Percent Tank emissions
tank_emsn <- print(all_3[1,2])
tank_95 <- (95/100)*tank_emsn 
print(paste("95 percent Tank Emission reduction is",tank_95, "Metric ton CH4"))

#80 percent fugitive emissions
all_rd_80 <- (80/100)* (all_3[8,2])
print(paste("80 percent Fugitive Emission reduction is",all_rd_80, "Metric ton CH4"))


#POLICY 2
p_ctrl_95 <- (95/100)*(all_3[2,2])
print(paste("95 percent percent Pneumatic controller Emission reduction is",p_ctrl_95, "Metric ton CH4"))


#40 percent fugitive emissions
all_rd_40 <- (40/100)* (all_3[8,2])
print(paste("40 percent Fugitive Emission reduction is",all_rd_40, "Metric ton CH4"))
```

